---
# Source: gocd/templates/deploy.yaml
format_version: 10
pipelines:
  build-equus-status-stag:
    group: xquare
    environment_variables:

    label_template: "${git[:7]}"
    materials:
      git:
        git: https://github.com/EntryDSM/Equus-Status
        shallow_clone: false
        auto_update: true
        branch: develop
    stages:
      - build:
          jobs:
            build:
              resources:
                - build
              artifacts:
                - build:
                    source: build_result.env
                    destination: artifacts
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - |
                        curl -o runtime_setting_and_build.sh https://raw.githubusercontent.com/team-xquare/xquare-gitops-repo-v2/main/script/runtime_setting_and_build.sh
                        curl -o template.json https://raw.githubusercontent.com/team-xquare/xquare-gitops-repo-v2/main/pipelines/stag/equus-status/template.json
                        chmod +x runtime_setting_and_build.sh
                        ./runtime_setting_and_build.sh template.json

                        curl -o docker_build.sh https://raw.githubusercontent.com/team-xquare/xquare-gitops-repo-v2/main/script/docker_build.sh
                        curl -o Dockerfile https://raw.githubusercontent.com/team-xquare/xquare-gitops-repo-v2/main/pipelines/stag/equus-status/Dockerfile
                        chmod +x docker_build.sh
                        ./docker_build.sh stag equus-status
      - deploy:
          jobs:
            deploy:
              elastic_profile_id: deploy-agent-profile
              tasks:
                - fetch:
                    run_if: any
                    artifact_origin: gocd
                    stage: build
                    job: build
                    is_file: yes
                    source: artifacts/build_result.env
                    destination: environment
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - |
                        cat environment/build_result.env
                        source environment/build_result.env

                        curl -o resource_deploy.sh https://raw.githubusercontent.com/team-xquare/xquare-gitops-repo-v2/main/script/resource_deploy.sh
                        chmod +x resource_deploy.sh
                        SANITIZED_NAME=$(echo equus-status | sed 's/-/_/g')
                        RESOURCE_VAR_NAME="${SANITIZED_NAME}_REPOSITORY"
                        ./resource_deploy.sh equus-status stag ${!RESOURCE_VAR_NAME}
