---
# Source: gocd/templates/elastic-agent-pvc.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: build-agent-storage-class
  namespace: gocd
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  iops: "3000"
  throughput: "125"
  fsType: ext4
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
---
# Source: gocd/templates/elastic-agent-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: gocd
  name: xquare-infra-test-stag-docker-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10G
  storageClassName: build-agent-storage-class
