FROM gradle:8-jdk{{ jdk_version }} AS build
ENV TZ=Asia/Seoul

COPY . .

{% for command in build_commands %}
RUN --mount=type=cache,target=/root/.gradle \
    {{ command }}
{% endfor %}

FROM openjdk:{{ jdk_version }}-jdk-slim
ENV TZ=Asia/Seoul

COPY --from=build {{ output_dir }} /app.jar

ENTRYPOINT ["java", "-jar", "/app.jar"]
