FROM openjdk:{{ jdk_version }}-jdk-slim AS build
ENV TZ=Asia/Seoul

COPY . .

{% for command in build_commands %}
RUN --mount=type=cache,target=/root/.gradle \
    {{ command }}
{% endfor %}

COPY {{ output_dir }} app.jar

FROM openjdk:{{ jdk_version }}-jdk-slim
ENV TZ=Asia/Seoul

COPY --from=build /app.jar /app.jar

ENTRYPOINT ["java", "-jar", "/app.jar"]
