{%- if builder == "node" %}
FROM node:{{ node_version }}

{% for command in build_commands %}
RUN {{ command }}
{% endfor %}

COPY . .

EXPOSE {{ port }}

{%- if command %}
CMD [
  {%- for arg in command.split() %}
  {%- if not loop.first %}, {% endif %}"{{ arg }}"
  {%- endfor %}]
{%- endif %}

{%- endif %}
