club: daedongyeojido
name: sillok
organization: Team-jeong-ho-kim
repository: Daedongyeojido_BE_v3
branch: main
environment: prod
containerPort: 8080
domain: sillok-server.xquare.app
language: java
critical_service: false
