---
# Source: applications/templates/poddistruptionbudget.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  namespace: entry-prod
  name: equus-api-gateway-prod
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: equus-api-gateway-prod
---
# Source: applications/templates/vaultsecret.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: equus-api-gateway-prod-account
  namespace: entry-prod
---
# Source: applications/templates/elastic-agent-pvc.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: build-agent-storage-class
  namespace: gocd
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  iops: "3000"
  throughput: "125"
  fsType: ext4
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
---
# Source: applications/templates/elastic-agent-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: gocd
  name: equus-api-gateway-prod-docker-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20G
  storageClassName: build-agent-storage-class
---
# Source: applications/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  namespace: entry-prod
  name: equus-api-gateway-prod
  labels:
    app: equus-api-gateway-prod
    project: equus-api-gateway
    environment: prod
spec:
  type: ClusterIP
  selector:
    app: equus-api-gateway-prod
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
    - name: port
      port: 8080
      targetPort: 8080
      protocol: TCP
---
# Source: applications/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: entry-prod
  name: equus-api-gateway-prod
  labels:
    app: equus-api-gateway-prod
    project: equus-api-gateway
    test: test
    environment: prod
spec:
  replicas: 1
  revisionHistoryLimit: 0
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: equus-api-gateway-prod
  template:
    metadata:      
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "false"
        sidecar.istio.io/proxyCPU: "5m"
        sidecar.istio.io/proxyMemory: "128Mi"
        instrumentation.opentelemetry.io/inject-java: "true"
      labels:
        app: equus-api-gateway-prod
        project: equus-api-gateway
    spec:
      serviceAccountName: equus-api-gateway-prod-account
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - equus-api-gateway-prod
              topologyKey: "kubernetes.io/hostname"
      nodeSelector:
        Karpenter: enabled
      tolerations:
        - effect: "NoSchedule"
          key: xquare/server
          operator: "Equal"
          value: "true"
      terminationGracePeriodSeconds: 120
      containers:
        - name: equus-api-gateway-prod
          image: 786584124104.dkr.ecr.ap-northeast-2.amazonaws.com/equus-api-gateway-prod:prod-aie0ze02
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
          - secretRef:
              name: equus-api-gateway-prod
          resources:
            requests:
              memory: "500Mi"
              cpu: "20m"
              ephemeral-storage: "20Mi"
            limits:
              memory: "2Gi"
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 3
---
# Source: applications/templates/datadog-dashboard.yaml
apiVersion: datadoghq.com/v1alpha1
kind: DatadogDashboard
metadata:
  name: equus-api-gateway-prod-dashboard
spec:
  title: Test
  description: null
  widgets: |
    [
      {
        "id": 8372280242358600,
        "definition": {
          "title": "Requests",
          "title_size": "16",
          "title_align": "left",
          "show_legend": true,
          "legend_layout": "auto",
          "legend_columns": ["avg", "min", "max", "value", "sum"],
          "time": {"type": "live", "unit": "hour", "value": 1},
          "type": "timeseries",
          "requests": [
            {
              "formulas": [{"formula": "query1"}],
              "queries": [
                {
                  "name": "query1",
                  "data_source": "spans",
                  "search": {"query": "service:equus-api-gateway-prod"},
                  "indexes": ["*"],
                  "group_by": [],
                  "compute": {"aggregation": "count"},
                  "storage": "hot"
                }
              ],
              "response_format": "timeseries",
              "style": {"palette": "dog_classic", "order_by": "values", "line_type": "solid", "line_width": "normal"},
              "display_type": "bars"
            }
          ]
        },
        "layout": {"x": 0, "y": 0, "width": 4, "height": 2}
      },
      {
        "id": 1828811240780074,
        "definition": {
          "title": "Erros",
          "title_size": "16",
          "title_align": "left",
          "show_legend": true,
          "legend_layout": "auto",
          "legend_columns": ["avg", "min", "max", "value", "sum"],
          "time": {"type": "live", "unit": "hour", "value": 1},
          "type": "timeseries",
          "requests": [
            {
              "formulas": [{"formula": "query1"}],
              "queries": [
                {
                  "name": "query1",
                  "data_source": "spans",
                  "search": {"query": "status:error service:equus-api-gateway-prod"},
                  "indexes": ["*"],
                  "group_by": [],
                  "compute": {"aggregation": "count"},
                  "storage": "hot"
                }
              ],
              "response_format": "timeseries",
              "style": {"palette": "red", "order_by": "values", "line_type": "solid", "line_width": "normal"},
              "display_type": "bars"
            }
          ]
        },
        "layout": {"x": 4, "y": 0, "width": 4, "height": 2}
      },
      {
        "id": 5950195771275574,
        "definition": {
          "title": "Latency",
          "title_size": "16",
          "title_align": "left",
          "show_legend": true,
          "legend_layout": "auto",
          "legend_columns": ["avg", "min", "max", "value", "sum"],
          "time": {"type": "live", "unit": "hour", "value": 1},
          "type": "timeseries",
          "requests": [
            {
              "formulas": [
                {"formula": "query1"},
                {"formula": "query2"},
                {"formula": "query3"},
                {"formula": "query4"},
                {"formula": "query5"}
              ],
              "queries": [
                {
                  "name": "query1",
                  "data_source": "spans",
                  "search": {"query": "service:equus-api-gateway-prod @duration:*"},
                  "indexes": ["*"],
                  "group_by": [],
                  "compute": {"aggregation": "pc99", "metric": "@duration"},
                  "storage": "hot"
                },
                {
                  "name": "query2",
                  "data_source": "spans",
                  "search": {"query": "service:equus-api-gateway-prod @duration:*"},
                  "indexes": ["*"],
                  "group_by": [],
                  "compute": {"aggregation": "pc98", "metric": "@duration"},
                  "storage": "hot"
                },
                {
                  "name": "query3",
                  "data_source": "spans",
                  "search": {"query": "service:equus-api-gateway-prod @duration:*"},
                  "indexes": ["*"],
                  "group_by": [],
                  "compute": {"aggregation": "pc95", "metric": "@duration"},
                  "storage": "hot"
                },
                {
                  "name": "query4",
                  "data_source": "spans",
                  "search": {"query": "service:equus-api-gateway-prod @duration:*"},
                  "indexes": ["*"],
                  "group_by": [],
                  "compute": {"aggregation": "pc90", "metric": "@duration"},
                  "storage": "hot"
                },
                {
                  "name": "query5",
                  "data_source": "spans",
                  "search": {"query": "service:equus-api-gateway-prod @duration:*"},
                  "indexes": ["*"],
                  "group_by": [],
                  "compute": {"aggregation": "pc75", "metric": "@duration"},
                  "storage": "hot"
                }
              ],
              "response_format": "timeseries",
              "style": {"palette": "dog_classic", "order_by": "values", "line_type": "solid", "line_width": "normal"},
              "display_type": "line"
            }
          ]
        },
        "layout": {"x": 8, "y": 0, "width": 4, "height": 2}
      },
      {
        "id": 556828742999416,
        "definition": {
          "title": "",
          "title_size": "16",
          "title_align": "left",
          "requests": [
            {
              "response_format": "event_list",
              "query": {
                "data_source": "issue_stream",
                "query_string": "service:equus-api-gateway-prod",
                "indexes": []
              },
              "columns": [
                {"field": "details", "width": "auto"},
                {"field": "count", "width": "auto"},
                {"field": "volume", "width": "auto"}
              ]
            }
          ],
          "type": "list_stream"
        },
        "layout": {"x": 0, "y": 2, "width": 12, "height": 3}
      },
      {
        "id": 4013092634840146,
        "definition": {
          "title": "Endpoint Breakdown",
          "title_size": "16",
          "title_align": "left",
          "type": "query_table",
          "requests": [
            {
              "queries": [
                {
                  "name": "query1",
                  "data_source": "spans",
                  "search": {"query": "service:equus-api-gateway-prod @duration:*"},
                  "indexes": ["*"],
                  "group_by": [
                    {
                      "facet": "resource_name",
                      "limit": 10,
                      "sort": {"aggregation": "avg", "order": "desc", "metric": "@duration"},
                      "should_exclude_missing": true
                    }
                  ],
                  "compute": {"aggregation": "avg", "metric": "@duration"},
                  "storage": "hot"
                }
              ],
              "response_format": "scalar",
              "sort": {"count": 10, "order_by": [{"type": "formula", "index": 0, "order": "desc"}]},
              "formulas": [{"formula": "query1", "cell_display_mode": "bar"}]
            }
          ],
          "has_search_bar": "auto"
        },
        "layout": {"x": 0, "y": 5, "width": 6, "height": 4}
      },
      {
        "id": 7641022191923658,
        "definition": {
          "time": {"type": "live", "unit": "hour", "value": 1},
          "title": "Status Treemap",
          "type": "treemap",
          "requests": [
            {
              "response_format": "scalar",
              "queries": [
                {
                  "name": "query1",
                  "data_source": "spans",
                  "search": {"query": "service:equus-api-gateway-prod"},
                  "indexes": ["*"],
                  "group_by": [
                    {
                      "facet": "@http.status_code",
                      "limit": 10,
                      "sort": {"aggregation": "count", "order": "desc", "metric": "count"},
                      "should_exclude_missing": true
                    }
                  ],
                  "compute": {"aggregation": "count"},
                  "storage": "hot"
                }
              ],
              "style": {"palette": "datadog16"},
              "formulas": [{"formula": "query1"}]
            }
          ]
        },
        "layout": {"x": 6, "y": 5, "width": 6, "height": 4}
      },
      {
        "id": 7839211518193048,
        "definition": {
          "title": "",
          "title_size": "16",
          "title_align": "left",
          "requests": [
            {
              "response_format": "event_list",
              "query": {
                "data_source": "trace_stream",
                "query_string": "service:equus-api-gateway-prod",
                "indexes": ["*"]
              },
              "columns": [
                {"field": "timestamp", "width": "auto"},
                {"field": "service", "width": "auto"},
                {"field": "resource_name", "width": "auto"},
                {"field": "@duration", "width": "auto"},
                {"field": "@http.method", "width": "auto"},
                {"field": "@http.status_code", "width": "auto"},
                {"field": "span_count", "width": "auto"},
                {"field": "latency_breakdown", "width": "auto"}
              ]
            }
          ],
          "type": "list_stream"
        },
        "layout": {"x": 0, "y": 9, "width": 12, "height": 6}
      }
    ]
  templateVariables:
    - name: trace
      prefix: trace
      availableValues: []
      defaults:
        - "*"
  layoutType: ordered
  notifyList: []
  reflowType: fixed
---
# Source: applications/templates/vaultsecret.yaml
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: equus-api-gateway-prod-auth
  namespace: entry-prod
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: xquare
    serviceAccount: equus-api-gateway-prod-account
    audiences:
      - vault
---
# Source: applications/templates/vaultsecret.yaml
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: equus-api-gateway-prod-secret
  namespace: entry-prod
spec:
  mount: xquare-kv
  path: equus-api-gateway-prod
  destination:
    name: equus-api-gateway-prod
    create: true
  hmacSecretData: true
  vaultAuthRef: entry-prod/equus-api-gateway-prod-auth
  refreshAfter: 1m
  rolloutRestartTargets:
    - kind: Deployment
      name: equus-api-gateway-prod
  type: kv-v1
---
# Source: applications/templates/vpa.yaml
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: equus-api-gateway-prod-vpa
  namespace: entry-prod
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       equus-api-gateway-prod
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
      - containerName: "*"
        controlledResources: [ "memory" ]
---
# Source: applications/templates/virtual-service.yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: equus-api-gateway-prod-domain-ingress
  labels:
    app.kubernetes.io/instance: xquare-ingress
  namespace: entry-prod
spec:
  gateways:
    - istio-system/xquare-ingressgateway
  hosts:
    - equus.xquare.app
  http:
    - name: equus-api-gateway
      route:
        - destination:
            host: 'equus-api-gateway-prod.entry-prod.svc.cluster.local'
            port:
              number: 8080
      corsPolicy:
        allowOrigins:
          - regex: ".*"
        allowMethods:
          - POST
          - GET
          - PUT
          - PATCH
          - DELETE
          - OPTIONS
        allowCredentials: true
        allowHeaders:
          - content-type
          - authorization
          - accept
          - accept-encoding
          - Refresh-Token
          - X-Not-Using-Xquare-Auth
          - Oauth-Token
          - oa-token
          - Request-User-Id
          - Request-User-Role
          - X-Refresh-Token
          - x-identifier
        maxAge: "24h"
