---
# Source: gocd/templates/pipeline.yaml
format_version: 11
pipelines:
  build-daemaru-stag:
    group: xquare
    environment_variables:

    label_template: "${git[:7]}"
    materials:
      git:
        git: https://github.com/daemaru/daemaru-backend
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - build:
          jobs:
            build:
              elastic_profile_id: daemaru-stag-agent-profile
              artifacts:
                - build:
                    source: build_result.env
                    destination: artifacts
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - |
                        curl -o template.json https://raw.githubusercontent.com/team-xquare/xquare-gitops-repo-v2/main/pipelines/stag/daemaru/template.json

                        curl -o docker_build.sh https://raw.githubusercontent.com/team-xquare/xquare-gitops-repo-v2/main/script/docker_build.sh
                        curl -o Dockerfile https://raw.githubusercontent.com/team-xquare/xquare-gitops-repo-v2/main/pipelines/stag/daemaru/Dockerfile
                        chmod +x docker_build.sh

                        ./docker_build.sh stag daemaru "$(cat template.json)"
      - deploy:
          jobs:
            deploy:
              elastic_profile_id: deploy-agent-profile
              tasks:
                - fetch:
                    run_if: any
                    artifact_origin: gocd
                    stage: build
                    job: build
                    is_file: yes
                    source: artifacts/build_result.env
                    destination: environment
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - |
                        cat environment/build_result.env
                        source environment/build_result.env

                        curl -o resource_deploy.sh https://raw.githubusercontent.com/team-xquare/xquare-gitops-repo-v2/main/script/resource_deploy.sh
                        chmod +x resource_deploy.sh
                        SANITIZED_NAME=$(echo daemaru | sed 's/-/_/g')
                        RESOURCE_VAR_NAME="${SANITIZED_NAME}_REPOSITORY"
                        ./resource_deploy.sh daemaru stag ${!RESOURCE_VAR_NAME}
