club: growingbegger
name: growing-begger
organization: GrowingBegger
repository: GE-BE
branch: develop
environment: stag
containerPort: 8080
domain: growing-begger-stag.xquare.app
language: java
critical_service: false
