---
# Source: applications/templates/poddistruptionbudget.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  namespace: mozu-stag
  name: mozu-server-stag
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: mozu-server-stag
---
# Source: applications/templates/vaultsecret.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mozu-server-stag-account
  namespace: mozu-stag
---
# Source: applications/templates/elastic-agent-pvc.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: build-agent-storage-class
  namespace: gocd
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  iops: "3000"
  throughput: "125"
  fsType: ext4
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
---
# Source: applications/templates/elastic-agent-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: gocd
  name: mozu-server-stag-docker-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20G
  storageClassName: build-agent-storage-class
---
# Source: applications/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  namespace: mozu-stag
  name: mozu-server-stag
  labels:
    app: mozu-server-stag
    project: mozu-server
    environment: stag
spec:
  type: ClusterIP
  selector:
    app: mozu-server-stag
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
    - name: port
      port: 3000
      targetPort: 3000
      protocol: TCP
---
# Source: applications/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mozu-stag
  name: mozu-server-stag
  labels:
    app: mozu-server-stag
    project: mozu-server
    test: test
    environment: stag
spec:
  replicas: 1
  revisionHistoryLimit: 0
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: mozu-server-stag
  template:
    metadata:      
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "false"
        sidecar.istio.io/proxyCPU: "5m"
        sidecar.istio.io/proxyMemory: "128Mi"
        instrumentation.opentelemetry.io/inject-nodejs: "true"
      labels:
        app: mozu-server-stag
        project: mozu-server
    spec:
      serviceAccountName: mozu-server-stag-account
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - mozu-server-stag
              topologyKey: "kubernetes.io/hostname"
      nodeSelector:
        Karpenter: enabled
      tolerations:
        - effect: "NoSchedule"
          key: xquare/server
          operator: "Equal"
          value: "true"
      terminationGracePeriodSeconds: 120
      containers:
        - name: mozu-server-stag
          image: 786584124104.dkr.ecr.ap-northeast-2.amazonaws.com/mozu-server-stag:stag-7nufz3fi
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          envFrom:
          - secretRef:
              name: mozu-server-stag
          resources:
            requests:
              memory: "500Mi"
              cpu: "20m"
              ephemeral-storage: "20Mi"
            limits:
              memory: "2Gi"
          readinessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 3
---
# Source: applications/templates/vaultsecret.yaml
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: mozu-server-stag-auth
  namespace: mozu-stag
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: xquare
    serviceAccount: mozu-server-stag-account
    audiences:
      - vault
---
# Source: applications/templates/vaultsecret.yaml
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: mozu-server-stag-secret
  namespace: mozu-stag
spec:
  mount: xquare-kv
  path: mozu-server-stag
  destination:
    name: mozu-server-stag
    create: true
  hmacSecretData: true
  vaultAuthRef: mozu-stag/mozu-server-stag-auth
  refreshAfter: 1m
  rolloutRestartTargets:
    - kind: Deployment
      name: mozu-server-stag
  type: kv-v1
---
# Source: applications/templates/vpa.yaml
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: mozu-server-stag-vpa
  namespace: mozu-stag
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       mozu-server-stag
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
      - containerName: "*"
        controlledResources: [ "memory" ]
---
# Source: applications/templates/virtual-service.yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: mozu-server-stag-domain-ingress
  labels:
    app.kubernetes.io/instance: xquare-ingress
  namespace: mozu-stag
spec:
  gateways:
    - istio-system/xquare-ingressgateway
  hosts:
    - mozu-stag.xquare.app
  http:
    - name: mozu-server
      route:
        - destination:
            host: 'mozu-server-stag.mozu-stag.svc.cluster.local'
            port:
              number: 3000
      corsPolicy:
        allowOrigins:
          - regex: ".*"
        allowMethods:
          - POST
          - GET
          - PUT
          - PATCH
          - DELETE
          - OPTIONS
        allowCredentials: true
        allowHeaders:
          - content-type
          - authorization
          - accept
          - accept-encoding
          - Refresh-Token
          - X-Not-Using-Xquare-Auth
          - Oauth-Token
          - oa-token
          - Request-User-Id
          - Request-User-Role
          - X-Refresh-Token
          - x-identifier
        maxAge: "24h"
