---
# Source: applications/templates/poddistruptionbudget.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  namespace: entry-prod
  name: equus-status-prod
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: equus-status-prod
---
# Source: applications/templates/vaultsecret.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: equus-status-prod-account
  namespace: entry-prod
---
# Source: applications/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  namespace: entry-prod
  name: equus-status-prod
  labels:
    app: equus-status-prod
    project: equus-status
    environment: prod
spec:
  type: ClusterIP
  selector:
    app: equus-status-prod
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
    - name: port
      port: 8080
      targetPort: 8080
      protocol: TCP
---
# Source: applications/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: entry-prod
  name: equus-status-prod
  labels:
    app: equus-status-prod
    project: equus-status
    test: test
    environment: prod
spec:
  replicas: 2
  revisionHistoryLimit: 0
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: equus-status-prod
  template:
    metadata:      
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "false"
        sidecar.istio.io/proxyCPU: "5m"
        sidecar.istio.io/proxyMemory: "128Mi"
        instrumentation.opentelemetry.io/inject-java: "true"
      labels:
        app: equus-status-prod
        project: equus-status
    spec:
      serviceAccountName: equus-status-prod-account
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - equus-status-prod
              topologyKey: "kubernetes.io/hostname"
      nodeSelector:
        Karpenter: enabled
      tolerations:
        - effect: "NoSchedule"
          key: xquare/critical_service
          operator: "Equal"
          value: "true"
      terminationGracePeriodSeconds: 120
      containers:
        - name: equus-status-prod
          image: 786584124104.dkr.ecr.ap-northeast-2.amazonaws.com/equus-status-prod:prod-r0nf4ac7
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
          - secretRef:
              name: equus-status-prod
          resources:
            requests:
              memory: "500Mi"
              cpu: "20m"
              ephemeral-storage: "20Mi"
            limits:
              memory: "2Gi"
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 3
---
# Source: applications/templates/vaultsecret.yaml
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: equus-status-prod-auth
  namespace: entry-prod
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: xquare
    serviceAccount: equus-status-prod-account
    audiences:
      - vault
---
# Source: applications/templates/vaultsecret.yaml
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: equus-status-prod-secret
  namespace: entry-prod
spec:
  mount: xquare-kv
  path: equus-status-prod
  destination:
    name: equus-status-prod
    create: true
  vaultAuthRef: entry-prod/equus-status-prod-auth
  rolloutRestartTargets:
    - kind: Deployment
      name: equus-status-prod
---
# Source: applications/templates/vpa.yaml
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: equus-status-prod-vpa
  namespace: entry-prod
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       equus-status-prod
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
      - containerName: "*"
        controlledResources: [ "memory" ]
