apiVersion: v1
kind: Pod
metadata:
  name: gocd-elastic-agent
spec:
  serviceAccountName: gocd
  securityContext:
    runAsUser: 0
    runAsGroup: 0
    fsGroup: 0
    fsGroupChangePolicy: "OnRootMismatch"
  containers:
    - name: gocd-build-agent
      image: 786584124104.dkr.ecr.ap-northeast-2.amazonaws.com/gocd-agent-docker-dind-with-awscli:latest
      imagePullPolicy: IfNotPresent
      securityContext:
        privileged: true
      resources:
        requests:
          cpu: 2000m
          memory: 7G
      env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: aws_access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: aws_secret_access_key
      volumeMounts:
        - name: aws-credentials
          mountPath: /etc/config/aws/
          readOnly: true
        - name: docker-volume
          mountPath: /var/lib/docker
        - name: gradle-volume
          mountPath: /root/.gradle
  volumes:
    - name: aws-credentials
      secret:
        secretName: aws-credentials
        defaultMode: 0744
    - name: docker-volume
      persistentVolumeClaim:
        claimName: {{ .Values.name }}-{{ .Values.environment }}-docker-pvc
    - name: gradle-volume
      persistentVolumeClaim:
        claimName: {{ .Values.name }}-{{ .Values.environment }}-application-pvc
  tolerations:
    - key: "xquare/server"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"