apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: gocd
  name: {{ .Values.name }}-{{ .Values.environment }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: gp2
