apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: gocd
  name: {{ .Values.name }}-{{ .Values.environment }}-docker-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2.5Gi
  storageClassName: gp2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: gocd
  name: {{ .Values.name }}-{{ .Values.environment }}-application-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2.5Gi
  storageClassName: gp2