club: daedongyeojido
name: sillok
organization: Team-jeong-ho-kim
repository: Daedongyeojido_BE_v3
branch: develop/sillok
environment: stag
containerPort: 8080
domain: sillok-stag-server.xquare.app
language: java
critical_service: false
