---
# Source: applications/templates/poddistruptionbudget.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  namespace: kook-prod
  name: kook-prod
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: kook-prod
---
# Source: applications/templates/vaultsecret.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kook-prod-account
  namespace: kook-prod
---
# Source: applications/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  namespace: kook-prod
  name: kook-prod
  labels:
    app: kook-prod
    project: kook
    environment: prod
spec:
  type: ClusterIP
  selector:
    app: kook-prod
  ports:
    - name: http
      port: 80
      targetPort: 8089
      protocol: TCP
    - name: port
      port: 8089
      targetPort: 8089
      protocol: TCP
---
# Source: applications/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kook-prod
  name: kook-prod
  labels:
    app: kook-prod
    project: kook
    test: test
    environment: prod
spec:
  replicas: 1
  revisionHistoryLimit: 0
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: kook-prod
  template:
    metadata:      
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "false"
        sidecar.istio.io/proxyCPU: "5m"
        sidecar.istio.io/proxyMemory: "128Mi"
        instrumentation.opentelemetry.io/inject-java: "true"
      labels:
        app: kook-prod
        project: kook
    spec:
      serviceAccountName: kook-prod-account
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - kook-prod
              topologyKey: "kubernetes.io/hostname"
      nodeSelector:
        Karpenter: enabled
      tolerations:
        - effect: "NoSchedule"
          key: xquare/server
          operator: "Equal"
          value: "true"
      terminationGracePeriodSeconds: 120
      containers:
        - name: kook-prod
          image: 786584124104.dkr.ecr.ap-northeast-2.amazonaws.com/kook-prod:prod-ei9te5db
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8089
          envFrom:
          - secretRef:
              name: kook-prod
          resources:
            requests:
              memory: "500Mi"
              cpu: "20m"
              ephemeral-storage: "20Mi"
            limits:
              memory: "2Gi"
          readinessProbe:
            tcpSocket:
              port: 8089
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 3
---
# Source: applications/templates/vaultsecret.yaml
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: kook-prod-auth
  namespace: kook-prod
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: xquare
    serviceAccount: kook-prod-account
    audiences:
      - vault
---
# Source: applications/templates/vaultsecret.yaml
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: kook-prod-secret
  namespace: kook-prod
spec:
  mount: xquare-kv
  path: kook-prod
  destination:
    name: kook-prod
    create: true
  vaultAuthRef: kook-prod/kook-prod-auth
  rolloutRestartTargets:
    - kind: Deployment
      name: kook-prod
---
# Source: applications/templates/vpa.yaml
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: kook-prod-vpa
  namespace: kook-prod
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       kook-prod
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
      - containerName: "*"
        controlledResources: [ "memory" ]
---
# Source: applications/templates/virtual-service.yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kook-prod-domain-ingress
  labels:
    app.kubernetes.io/instance: xquare-ingress
  namespace: kook-prod
spec:
  gateways:
    - istio-system/xquare-ingressgateway
  hosts:
    - kook.xquare.app
  http:
    - name: kook
      route:
        - destination:
            host: 'kook-prod.kook-prod.svc.cluster.local'
            port:
              number: 8089
      corsPolicy:
        allowOrigins:
          - regex: ".*"
        allowMethods:
          - POST
          - GET
          - PUT
          - PATCH
          - DELETE
          - OPTIONS
        allowCredentials: true
        allowHeaders:
          - content-type
          - authorization
          - accept
          - accept-encoding
          - Refresh-Token
          - X-Not-Using-Xquare-Auth
          - Oauth-Token
          - oa-token
          - Request-User-Id
          - Request-User-Role
          - X-Refresh-Token
          - x-identifier
        maxAge: "24h"
