club: moatikon
name: moatikon
organization: moatikon
repository: moatikon_backend_v2
branch: develop
environment: stag
containerPort: 8764
domain: moatikon-stag.xquare.app
language: nodejs
critical_service: false
