---
# Source: applications/templates/poddistruptionbudget.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  namespace: pick-prod
  name: pick-android-bot-prod
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: pick-android-bot-prod
---
# Source: applications/templates/vaultsecret.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pick-android-bot-prod-account
  namespace: pick-prod
---
# Source: applications/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  namespace: pick-prod
  name: pick-android-bot-prod
  labels:
    app: pick-android-bot-prod
    project: pick-android-bot
    environment: prod
spec:
  type: ClusterIP
  selector:
    app: pick-android-bot-prod
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
    - name: port
      port: 3000
      targetPort: 3000
      protocol: TCP
---
# Source: applications/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: pick-prod
  name: pick-android-bot-prod
  labels:
    app: pick-android-bot-prod
    project: pick-android-bot
    test: test
    environment: prod
spec:
  replicas: 1
  revisionHistoryLimit: 0
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: pick-android-bot-prod
  template:
    metadata:      
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "false"
        sidecar.istio.io/proxyCPU: "5m"
        sidecar.istio.io/proxyMemory: "128Mi"
      labels:
        app: pick-android-bot-prod
        project: pick-android-bot
    spec:
      serviceAccountName: pick-android-bot-prod-account
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - pick-android-bot-prod
              topologyKey: "kubernetes.io/hostname"
      nodeSelector:
        Karpenter: enabled
      tolerations:
        - effect: "NoSchedule"
          key: xquare/server
          operator: "Equal"
          value: "true"
      terminationGracePeriodSeconds: 120
      containers:
        - name: pick-android-bot-prod
          image: 786584124104.dkr.ecr.ap-northeast-2.amazonaws.com/pick-android-bot-prod:prod-xe6hswq3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          envFrom:
          - secretRef:
              name: pick-android-bot-prod
          resources:
            requests:
              memory: "500Mi"
              cpu: "20m"
              ephemeral-storage: "20Mi"
            limits:
              memory: "2Gi"
          readinessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 3
---
# Source: applications/templates/vaultsecret.yaml
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: pick-android-bot-prod-auth
  namespace: pick-prod
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: xquare
    serviceAccount: pick-android-bot-prod-account
    audiences:
      - vault
---
# Source: applications/templates/vaultsecret.yaml
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: pick-android-bot-prod-secret
  namespace: pick-prod
spec:
  mount: xquare-kv
  path: pick-android-bot-prod
  destination:
    name: pick-android-bot-prod
    create: true
  vaultAuthRef: pick-prod/pick-android-bot-prod-auth
  rolloutRestartTargets:
    - kind: Deployment
      name: pick-android-bot-prod
---
# Source: applications/templates/vpa.yaml
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: pick-android-bot-prod-vpa
  namespace: pick-prod
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       pick-android-bot-prod
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
      - containerName: "*"
        controlledResources: [ "memory" ]
---
# Source: applications/templates/virtual-service.yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: pick-android-bot-prod-domain-ingress
  labels:
    app.kubernetes.io/instance: xquare-ingress
  namespace: pick-prod
spec:
  gateways:
    - istio-system/xquare-ingressgateway
  hosts:
    - pick-android-bot.xquare.app
  http:
    - name: pick-android-bot
      route:
        - destination:
            host: 'pick-android-bot-prod.pick-prod.svc.cluster.local'
            port:
              number: 3000
      corsPolicy:
        allowOrigins:
          - regex: ".*"
        allowMethods:
          - POST
          - GET
          - PUT
          - PATCH
          - DELETE
          - OPTIONS
        allowCredentials: true
        allowHeaders:
          - content-type
          - authorization
          - accept
          - accept-encoding
          - Refresh-Token
          - X-Not-Using-Xquare-Auth
          - Oauth-Token
          - oa-token
          - Request-User-Id
          - Request-User-Role
          - X-Refresh-Token
          - x-identifier
        maxAge: "24h"
