{{- $fullname := (printf "%s-%s" .Values.name .Values.environment) }}

apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: {{ $fullname }}-auth
  namespace: {{ .Values.club }}-{{ .Values.environment }}
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: xquare
    serviceAccount: {{ $fullname }}-account
    audiences:
      - vault
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ $fullname }}-secret
  namespace: {{ .Values.club }}-{{ .Values.environment }}
spec:
  mount: xquare-kv
  path: {{ $fullname }}
  destination:
    name: {{ $fullname }}
    create: true
  hmacSecretData: true
  vaultAuthRef: {{ .Values.club }}-{{ .Values.environment }}/{{ $fullname }}-auth
  refreshAfter: 1m
  rolloutRestartTargets:
    - kind: Deployment
      name: {{ $fullname }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $fullname }}-account
  namespace: {{ .Values.club }}-{{ .Values.environment }}
