---
# Source: applications/templates/poddistruptionbudget.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  namespace: swing-stag
  name: swingbe-stag
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: swingbe-stag
---
# Source: applications/templates/vaultsecret.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: swingbe-stag-account
  namespace: swing-stag
---
# Source: applications/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  namespace: swing-stag
  name: swingbe-stag
  labels:
    app: swingbe-stag
    project: swingbe
    environment: stag
spec:
  type: ClusterIP
  selector:
    app: swingbe-stag
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
    - name: port
      port: 8080
      targetPort: 8080
      protocol: TCP
---
# Source: applications/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: swing-stag
  name: swingbe-stag
  labels:
    app: swingbe-stag
    project: swingbe
    test: test
    environment: stag
spec:
  replicas: 1
  revisionHistoryLimit: 0
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: swingbe-stag
  template:
    metadata:      
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "false"
        sidecar.istio.io/proxyCPU: "5m"
        sidecar.istio.io/proxyMemory: "128Mi"
        instrumentation.opentelemetry.io/inject-java: "true"
      labels:
        app: swingbe-stag
        project: swingbe
    spec:
      serviceAccountName: swingbe-stag-account
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - swingbe-stag
              topologyKey: "kubernetes.io/hostname"
      nodeSelector:
        Karpenter: enabled
      tolerations:
        - effect: "NoSchedule"
          key: xquare/server
          operator: "Equal"
          value: "true"
      terminationGracePeriodSeconds: 120
      containers:
        - name: swingbe-stag
          image: 786584124104.dkr.ecr.ap-northeast-2.amazonaws.com/swingbe-stag:stag-5sl1p452
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
          - secretRef:
              name: swingbe-stag
          resources:
            requests:
              memory: "500Mi"
              cpu: "20m"
              ephemeral-storage: "20Mi"
            limits:
              memory: "2Gi"
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 3
---
# Source: applications/templates/vaultsecret.yaml
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: swingbe-stag-auth
  namespace: swing-stag
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: xquare
    serviceAccount: swingbe-stag-account
    audiences:
      - vault
---
# Source: applications/templates/vaultsecret.yaml
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: swingbe-stag-secret
  namespace: swing-stag
spec:
  mount: xquare-kv
  path: swingbe-stag
  destination:
    name: swingbe-stag
    create: true
  vaultAuthRef: swing-stag/swingbe-stag-auth
  rolloutRestartTargets:
    - kind: Deployment
      name: swingbe-stag
---
# Source: applications/templates/vpa.yaml
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: swingbe-stag-vpa
  namespace: swing-stag
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       swingbe-stag
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
      - containerName: "*"
        controlledResources: [ "memory" ]
---
# Source: applications/templates/virtual-service.yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: swingbe-stag-domain-ingress
  labels:
    app.kubernetes.io/instance: xquare-ingress
  namespace: swing-stag
spec:
  gateways:
    - istio-system/xquare-ingressgateway
  hosts:
    - swing-be-stag.xquare.app
  http:
    - name: swingbe
      route:
        - destination:
            host: 'swingbe-stag.swing-stag.svc.cluster.local'
            port:
              number: 8080
      corsPolicy:
        allowOrigins:
          - regex: ".*"
        allowMethods:
          - POST
          - GET
          - PUT
          - PATCH
          - DELETE
          - OPTIONS
        allowCredentials: true
        allowHeaders:
          - content-type
          - authorization
          - accept
          - accept-encoding
          - Refresh-Token
          - X-Not-Using-Xquare-Auth
          - Oauth-Token
          - oa-token
          - Request-User-Id
          - Request-User-Role
          - X-Refresh-Token
          - x-identifier
        maxAge: "24h"
