name: Delete Kubernetes Resources

on:
  push:
    paths:
      - 'pipelines/prod/**'
      - 'pipelines/stag/**'

jobs:
  delete-resources:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get deleted files
        run: ./../../scripts/get_deleted_files.sh

      - name: Process deleted manifests
        if: always()
        run: ./../../scripts/process_deleted_manifests.sh
