name: Delete Kubernetes Resources

on:
  push:
    paths:
      - 'pipelines/**/**'

jobs:
  delete-resources:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name xquare-v3-cluster

      - name: Delete Kubernetes resources
        run: ./scripts/delete_kubernetes_resources.sh
