name: sync-pipeline
on:
  push:
    paths:
      - 'templates/gocd/templates/**'
jobs:
  ci:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: false
    
    steps:
      - name: Check Out The Repository
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Grant execute permission for script
        run: chmod +x ./script/generate_pipeline.sh

      - name: Pull latest changes
        run: git pull origin main

      - name: Validate
        run: ./script/generate_pipeline.sh

      - name: Commit The New Image Reference
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "release :: deploy pipeline"
          branch: main
          commit_options: '--no-verify --signoff'
          repository: .
          commit_user_name: XQUARE GitOps Bot
          commit_user_email: teamxquare@gmail.com
          commit_author: XQUARE GitOps Bot <teamxquare@gmail.com>
